# Generated by Django 4.0.5 on 2022-07-04 16:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_category_slug_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='category_image'),
        ),
    ]
