# Generated by Django 4.0.6 on 2022-07-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_order_is_fullfilled_order_order_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
