# Generated by Django 4.0.5 on 2022-07-04 12:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
