# Generated by Django 4.0.5 on 2022-07-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
