# Generated by Django 4.0.6 on 2022-07-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='business_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
